import './globals.css'
import Nav from './components/Nav'
import {getServerSession} from 'next-auth'
import { authOptions } from '@/pages/api/auth/[...nextauth]'
import Hydrate from './components/Hydrate'


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  //fetch the user
  const session = await getServerSession(authOptions)
  console.log(session)
  return (
    <html lang="en">
      <body className='mx-24'>
        <Hydrate>
        <Nav user={session?.user} expires={session?.expires as string}/>
        {children}
        </Hydrate>
        </body>
    </html>
  )
}
